[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
albums = { path = "../albums"}
chrono = "0.4.39"
metamodel = { path = "../metamodel"}
rusqlite = "0.32.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
uuid = "1.11.1"
